//! Inspector state-machine tests (§9 layer 1) on the checked-in
//! `fixtures/inspect` scenario: real artifacts generated by the driver
//! from the sample kernels, then reviewed.

use std::path::{Path, PathBuf};

use reconverge_tui::inspect::data::{self, InspectorData};
use reconverge_tui::inspect::state::{InspectorState, KeyAction};

fn fixture_data() -> InspectorData {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/inspect");
    let paths: Vec<PathBuf> = vec![dir.join("unimap.json"), dir.join("findings.json")];
    let data = data::load(&paths);
    assert!(
        data.errors.is_empty(),
        "fixture must load: {:?}",
        data.errors
    );
    data
}

#[test]
fn initial_state_selects_the_first_listed_value() {
    let data = fixture_data();
    let state = InspectorState::new(&data);
    assert_eq!(
        data.functions[state.function].function.name,
        "divergent_barrier"
    );
    assert_eq!(state.selected, "_1", "the `out` parameter comes first");
    assert_eq!(state.finding, None);
}

#[test]
fn value_selection_moves_and_wraps() {
    let data = fixture_data();
    let mut state = InspectorState::new(&data);
    assert!(state.update(KeyAction::NextValue, &data));
    assert_eq!(state.selected, "_3"); // `i`
    assert!(state.update(KeyAction::NextValue, &data));
    assert_eq!(state.selected, "_14"); // `e`
    assert!(state.update(KeyAction::NextValue, &data));
    assert_eq!(state.selected, "_1", "wraps to the top");
    assert!(state.update(KeyAction::PrevValue, &data));
    assert_eq!(state.selected, "_14", "wraps backwards too");
}

#[test]
fn provenance_walk_moves_toward_the_source_and_back() {
    let data = fixture_data();
    let mut state = InspectorState::new(&data);
    state.update(KeyAction::NextValue, &data);
    state.update(KeyAction::NextValue, &data);
    assert_eq!(state.selected, "_14");

    assert!(state.update(KeyAction::WalkProvenance, &data));
    assert_eq!(state.selected, "_11", "one hop toward the source");
    assert_eq!(state.history, vec!["_14".to_string()]);

    assert!(state.update(KeyAction::WalkBack, &data));
    assert_eq!(state.selected, "_14");
    assert!(state.history.is_empty());
}

#[test]
fn walking_a_source_is_a_no_op() {
    let data = fixture_data();
    let mut state = InspectorState::new(&data);
    state.update(KeyAction::NextValue, &data);
    assert_eq!(state.selected, "_3", "`i` is a thread-index source");
    assert!(
        !state.update(KeyAction::WalkProvenance, &data),
        "sources have no incoming provenance"
    );
    assert_eq!(state.selected, "_3");
}

#[test]
fn finding_jumps_land_on_the_relevant_value() {
    let data = fixture_data();
    assert_eq!(data.findings.len(), 3);
    let mut state = InspectorState::new(&data);

    // Finding 1: RC005 in `scale` — switches function.
    assert!(state.update(KeyAction::NextFinding, &data));
    assert_eq!(state.finding, Some(0));
    assert_eq!(data.functions[state.function].function.name, "scale");

    // Finding 2: RC005 in `divergent_barrier` — empty provenance falls
    // back to the first listed value.
    assert!(state.update(KeyAction::NextFinding, &data));
    assert_eq!(
        data.functions[state.function].function.name,
        "divergent_barrier"
    );
    assert_eq!(state.selected, "_1");

    // Finding 3: RC001 — lands on the divergent branch condition.
    assert!(state.update(KeyAction::NextFinding, &data));
    assert_eq!(state.finding, Some(2));
    assert_eq!(data.findings[2].code, "RC001");
    assert_eq!(state.selected, "_5");

    // Wraps, and N goes backwards.
    assert!(state.update(KeyAction::NextFinding, &data));
    assert_eq!(state.finding, Some(0));
    assert!(state.update(KeyAction::PrevFinding, &data));
    assert_eq!(state.finding, Some(2));
}

#[test]
fn function_cycling_resets_the_selection() {
    let data = fixture_data();
    let mut state = InspectorState::new(&data);
    state.update(KeyAction::NextValue, &data);
    assert!(state.update(KeyAction::NextFunction, &data));
    assert_eq!(data.functions[state.function].function.name, "scale");
    assert!(state.history.is_empty());
    assert!(state.update(KeyAction::NextFunction, &data));
    assert_eq!(
        data.functions[state.function].function.name,
        "divergent_barrier"
    );
    assert_eq!(state.selected, "_1");
}

/// The T1 gate property, checked headlessly: the RC001 finding's chain is
/// navigable in the unimap from the branch condition down to a
/// thread-index source.
#[test]
fn rc001_chain_is_complete_and_navigable() {
    let data = fixture_data();
    let mut state = InspectorState::new(&data);
    for _ in 0..3 {
        state.update(KeyAction::NextFinding, &data);
    }
    assert_eq!(data.findings[state.finding.unwrap()].code, "RC001");

    // Walk until a source; must terminate at the `i` witness.
    let mut hops = 0;
    while state.update(KeyAction::WalkProvenance, &data) {
        hops += 1;
        assert!(hops <= 32, "chain must terminate");
    }
    assert_eq!(state.selected, "_3", "the chain ends at the witness `i`");
    let f = &data.functions[state.function];
    let index = f.value_index("_3").unwrap();
    assert_eq!(
        f.function.values[index].source,
        Some(reconverge_artifacts::unimap::ValueSource::ThreadIndex)
    );
    assert!(hops >= 2, "a real chain, not a single hop");
}
