[package]
name = "reconverge-dialect-oxide"
description = "SIMT dialect definition for kernels written using cuda-oxide"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
readme = "README.md"
keywords = ["gpu", "cuda", "simt"]
categories = ["development-tools"]

[dependencies]
reconverge-core = { path = "../reconverge-core", version = "0.1.9" }
